export enum ActionsEnum {
    ADD_TO_BANK = 'ADD_TO_BANK',
    REMOVE_FROM_BANK = 'REMOVE_FROM_BANK',
    CLEAR_BANK = 'CLEAR_BANK',
    DROP_SELECTION = 'DROP_SELECTION',
    ATTACK_PIECE = 'ATTACK_PIECE',
    SELECT_PIECE = 'SELECT_PIECE',
    SET_MODE = 'SET_MODE',
    UPDATE_CELLS = 'UPDATE_CELLS',
    SET_FIELD = 'SET_FIELD',
    TOGGLE_TURN = 'TOGGLE_TURN',
}