export enum ActionsEnum {
    ADD_TO_BANK = 'ADD_TO_BANK',
    REMOVE_FROM_BANK = 'REMOVE_FROM_BANK',
    DROP_SELECTION = 'DROP_SELECTION',
    ATTACK_PIECE = 'ATTACK_PIECE',
    SELECT_PIECE = 'SELECT_PIECE',
}