export enum Cards {
	BOMB = "BOMB",
	CAPTAIN = "CAPTAIN",
	COLONEL = "COLONEL",
	FLAG = "FLAG",
	GENERAL = "GENERAL",
	LIEUTENANT = "LIEUTENANT",
	MAJOR = "MAJOR",
	MARSHAL = "MARSHAL",
	MINER = "MINER",
	SCOUT = "SCOUT",
	SERGEANT = "SERGEANT",
	SPY = "SPY",
}
